<?php
/**
 * Magiccart 
 * @category 	Magiccart 
 * @copyright 	Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license 	http://www.magiccart.net/license-agreement.html
 * @Author: Magiccart<team.magiccart@gmail.com>
 * @@Create Date: 2014-04-25 13:15:04
 * @@Modify Date: 2014-08-27 18:36:01
 * @@Function:
 */
?>
<?php echo $this->getChildHtml('amenu') ?>
<?php //echo $this->getChildHtml('vmenu') ?>
<script type="text/javascript">
    jQuery(document).ready(function($) {
        $(".nav-accordion").magicaccordion({
            accordion:true,
            speed: 400,
            closedSign: 'collapse',
            openedSign: 'expand',
            easing: 'easeInOutQuad'
        });
    });
</script>

