<?php
/**
 * MageWorx
 * MageWorx Extended Reports Extension
 * 
 * @category   MageWorx
 * @package    MageWorx_Xreports
 * @copyright  Copyright (c) 2015 MageWorx (http://www.mageworx.com/)
 */
?>

<div class="dashboard-tab-container">
    <?php echo $this->getChildHtml('periodicStats'); ?>
</div>

<div class="dashboard-tab-separator"></div>

<script type="text/javascript">
    $('xreports_tabs_periodic').setStyle({display: 'none'});
</script>