<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" >
<head>   
</head>
<body>
	Please Wait..
    <form id="amzpay" method="get" action="<?php echo $this->getUrl('amzpay/redirect/post');?>">
		<?php
			foreach ($_GET as $key => $value) {
				echo "<input type='hidden' name='$key' value='$value'/>";
			}
		?>
	</form>
	<script type="text/javascript">
		document.getElementById('amzpay').submit();
	</script>
</body>
</html>