<?php
/**
 * MageWorx
 * MageWorx Extended Reports Extension
 * 
 * @category   MageWorx
 * @package    MageWorx_Xreports
 * @copyright  Copyright (c) 2015 MageWorx (http://www.mageworx.com/)
 */
?>
<button onclick="applyMargin(); return false;"><span><span>Apply Margin</span></span></button>
<script type="text/javascript">
    function applyMargin() {

        cost = parseFloat($("cost").value);
        margin = parseFloat($("margin").value);
        if (isNaN(cost) || isNaN(margin) || cost <= 0){
            alert("<?php echo Mage::helper('mageworx_xreports')->__('Sales Margin cannot be applied') ?>");
        } else {
            newPrice = cost + cost * margin / 100;
            newPrice = parseFloat(newPrice).toFixed(2);
            if(!isNaN(newPrice) && newPrice > 0) {
                $("price").setValue(newPrice);
            }
        }
    }
</script>