<?php $status = $this->getStatus() ?>
<table class="form-list">
    <tr>
        <td class="scope-label" style="width:176px">
            <?php if ($status==Aitoc_Aitpagecache_Model_Warmup::STATUS_NOT_CACHED): ?>
                <button onclick="setLocation('<?php echo $this->getWarmupStartUrl() ?>')" type="button" class="scalable"><span><?php echo $this->__('Start Warm-Up Cache') ?></span></button>
            <?php elseif ($status==Aitoc_Aitpagecache_Model_Warmup::STATUS_IN_PROGRESS): ?>
                <button onclick="setLocation('<?php echo $this->getWarmupStopUrl() ?>')" type="button" class="scalable"><span><?php echo $this->__('Pause Warm-Up Cache') ?></span></button>
            <?php elseif ($status==Aitoc_Aitpagecache_Model_Warmup::STATUS_STOPPED): ?>
                <button onclick="setLocation('<?php echo $this->getWarmupContinueUrl() ?>')" type="button" class="scalable"><span><?php echo $this->__('Continue Warm-Up Cache') ?></span></button>
            <?php elseif ($status==Aitoc_Aitpagecache_Model_Warmup::STATUS_ALL_CACHED || $status==Aitoc_Aitpagecache_Model_Warmup::STATUS_CRON_DISABLED): ?>
                <button onclick="setLocation('<?php echo $this->getWarmupStartUrl() ?>')" type="button" class="scalable"><span><?php echo $this->__('Re-start Warm-Up Cache') ?></span></button>
            <?php endif; ?>
        </td>
        <td class="scope-label">
            <?php echo $this->getStatusText() ?>
        </td>
    </tr>
    <?php if ($status==Aitoc_Aitpagecache_Model_Warmup::STATUS_STOPPED): ?>
        <tr>
            <td class="scope-label">
                <button onclick="setLocation('<?php echo $this->getWarmupStartUrl() ?>')" type="button" class="scalable"><span><?php echo $this->__('Re-start Warm-Up Cache') ?></span></button>
            </td>
        </tr>
    <?php endif; ?>
    <tr>
        <td colspan=2  class="scope-label">
            <?php echo $this->__('Click to launch Cache Warm-up process which caches pages by cron based on URL Rewrites table.') ?>
            <?php echo $this->__('You can set the number of pages to be cached at a time via cron <a href="%s" target="_blank">here</a>', $this->getSystemConfigurationUrl()) ?>
        </td>
    </tr>
</table>
